### ISSUE TITLE
Error when running nethunter.py as root

### ISSUE THREAD

**Issue by grennault** [Shubhamvis98/nethunter-pinephone#5]
Hello,

When I try to run `sudo python nethunter.py` on my PinePhone (under unofficial Kali linux OS) I obtain the following error:
`Authorization required, but no authorization protocol specified` (x3)
`(nethunter.py:2401): Gtk-WARNING **: [...] cannot open display :  :0`

NOTE: when running as kali user the `python nethunter.py` command well opens the app. 

Thank you very much for your help.

**Comment by Shubhamvis98** [comment]
> Hello,
> 
> When I try to run `sudo python nethunter.py` on my PinePhone (under unofficial Kali linux OS) I obtain the following error: `Authorization required, but no authorization protocol specified` (x3) `(nethunter.py:2401): Gtk-WARNING **: [...] cannot open display : :0`
> 
> NOTE: when running as kali user the `python nethunter.py` command well opens the app.
> 
> Thank you very much for your help.

execute `python nethunter.py` through root shell instead of sudo

**Comment by Shubhamvis98** [comment]
the cannot open display warning is due to wayland windows server. i haven't worked on this as of now but I'll try to fix it so we can use it with sudo or pkexec.

**Comment by grennault** [comment]
Thanks for your quick reply.

> execute `python nethunter.py` through root shell instead of sudo

I tried but I obtain the same error as when running with sudo.

**Comment by Shubhamvis98** [comment]
> Thanks for your quick reply.
> 
> > execute `python nethunter.py` through root shell instead of sudo
> 
> I tried but I obtain the same error as when running with sudo.

run `su` first to switch to root shell
then execute `python nethunter.py` without sudo

**Comment by grennault** [comment]
> run `su` first to switch to root shell
> then execute `python nethunter.py` without sudo

I tried `su` (with pwd 8888) but I obtain a `su: Authentication failure`. But I believe that's normal as I must run this command with sudo. 
I tried `sudo su` (with pwd 8888) then execute (thus as root shell - `root@kali`) `python nethunter.py` without sudo. Still same problem.

**Comment by Shubhamvis98** [comment]
> > run `su` first to switch to root shell
> > then execute `python nethunter.py` without sudo
> 
> I tried `su` (with pwd 8888) but I obtain a `su: Authentication failure`. But I believe that's normal as I must run this command with sudo. I tried `sudo su` then execute (as root shell - `root@kali`) `python nethunter.py` without sudo. Still same problem.

You should set root password first. Or switch to root shell using `sudo su` and enter 8888 as password.

**Comment by grennault** [comment]
> You should set root password first. Or switch to root she'll using `sudo su` and enter 8888 as password.

Thanks ! Set the root password did the trick. There's no root account by default that was this right ?

I still have some errors (`Error creating proxy: The connection is closed (g-io-error-quark)` and `dconf-WARNING **: s to dconf: The connetion is closed`), but the app seems to work great. Amazing job.

**Comment by Shubhamvis98** [comment]
> > You should set root password first. Or switch to root she'll using `sudo su` and enter 8888 as password.
> 
> Thanks ! reset the root password (set it again to 8888) did the trick, but I don't get why tho.
> 
> I still have some errors (`Error creating proxy: The connection is closed (g-io-error-quark)` and `dconf-WARNING **: s to dconf: The connetion is closed`), but the app seems to work great. Amazing job.

You can ignore that error.

**Comment by Shubhamvis98** [comment]
this issue was already fixed so closing it.
